### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nebrius** [sesh-kebab/raspi-sonar#2]
Before we can integrate this into raspi-io, we'll need to get an open source license in place. It's totally up to you which license you go with, as long as it's MIT compatible (or MIT itself).

If you do decide to go with the MIT license, feel free to borrow the licensing structure from [raspi-gpio](https://github.com/nebrius/raspi-gpio), which is structurally very similar to this module. Specifically, there is a [LICENSE](https://github.com/nebrius/raspi-gpio/blob/master/LICENSE) file, the contents of the license are added to the end of the [README](https://github.com/nebrius/raspi-gpio/blob/master/README.md#license), and the contents of license are also added as a comment to the top of every source code file, [like this](https://github.com/nebrius/raspi-gpio/blob/master/src/init.h#L1-L23).

**Comment by sesh-kebab** [comment]
Sure MIT license works for me. About copying the contents of the license to prepend to each source file; is this definitely necessary? 

If it is necessary, can there be a compromise made in terms of having a link to the LICENSE file on a single line text?

**Comment by nebrius** [comment]
ideally yeah, it would go in every file (and I add it to everyone of my files), but you can leave it out and just drop it in LICENSE and README.md if you prefer.

**Comment by sesh-kebab** [comment]
[Committed](https://github.com/sesh-kebab/raspi-sonar/commit/dab685d94c99376137b8bf43e0137986598117c4) new LICENSE file and updated existing  README.md
