### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nebrius** [sesh-kebab/raspi-sonar#3]
I would like to link to this repo from the [raspi README](https://github.com/nebrius/raspi#raspijs) like I do with the other peripheral classes, but before I do, can you put some documentation together?

I typically include three sections in the README: installation, example usage, and the API. Check out [raspi-gpio](https://github.com/nebrius/raspi-gpio/blob/master/README.md#installation) for some examples. Good docs go a long way towards getting people to use our stuff! :)

**Comment by sesh-kebab** [comment]
[PR 4](https://github.com/sesh-kebab/raspi-sonar/pull/4), containing the updated to documentation has been pulled in.
